name: learn_dart_library
description: This library is intended for educational purpose
version: 1.2.0 # update for sayHello
repository: https://github.com/devdezzies/learn_dart_library
homepage: https://www.abdullahspace.me

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
